### ISSUE TITLE
kitty test fails when any output line ends with a space character

### ISSUE THREAD

**Issue by JoachimBorup** [KongBorup/kitty#11]
If my program outputs any lines with an extra space at the end, e.g. "1 Abracadabra ", kitty fails the answer.

Here is the .txt file containing the expected answer for the first sample case in the problem with ID "timeloop":
[a.txt](https://github.com/KongBorup/kitty/files/5752593/a.txt)

**Comment by KongBorup** [comment]
To further document this issue, I have tested a bit further. Kattis accepts all of the following:
 - `"1 Abracadabra"`
 - `" 1 Abracadabra"`
 - `"1 Abracadabra "`

This suggests that Kattis strips all whitespace on both sides of each and every line. I will update kitty to behave in the same way.
